part of "theme.dart";

/// Generated by Forui CLI.
///
/// Color tokens and theme extensions for the generated theme.
final FColors lightColors = FColors(
  brightness: .light,
  systemOverlayStyle: .dark,
  barrier: const Color(0x33000000),
  background: _palette.spaceIndigo50,
  foreground: _palette.spaceIndigo900,
  primary: _palette.violet500,
  primaryForeground: _palette.violet50,
  secondary: _palette.sky500,
  secondaryForeground: _palette.sky950,
  muted: _palette.spaceIndigo100,
  mutedForeground: _palette.spaceIndigo400,
  destructive: _palette.strawberry500,
  destructiveForeground: _palette.strawberry50,
  error: _palette.strawberry500,
  errorForeground: _palette.strawberry50,
  card: _palette.spaceIndigo50,
  border: _palette.spaceIndigo200,
  extensions: const [PaletteColors()],
);

final FColors darkColors = FColors(
  brightness: .dark,
  systemOverlayStyle: .light,
  barrier: const Color(0x7A000000),
  background: _palette.spaceIndigo950,
  foreground: _palette.spaceIndigo50,
  primary: _palette.violet500,
  primaryForeground: _palette.violet50,
  secondary: _palette.sky400,
  secondaryForeground: _palette.sky950,
  muted: _palette.spaceIndigo800,
  mutedForeground: _palette.spaceIndigo300,
  destructive: _palette.strawberry400,
  destructiveForeground: _palette.strawberry950,
  error: _palette.strawberry400,
  errorForeground: _palette.strawberry950,
  card: _palette.spaceIndigo900,
  border: _palette.spaceIndigo700,
  extensions: const [PaletteColors()],
);

const _palette = PaletteColors();
