part of "theme.dart";

/// Generated by Forui CLI.
///
/// Style tokens and theme extensions for the generated theme.
FStyle _style({required FColors colors, required FTypography typography, required bool touch}) {
  const borderRadius = FBorderRadius();
  return FStyle(
    formFieldStyle: .inherit(colors: colors, typography: typography, touch: touch),
    focusedOutlineStyle: FFocusedOutlineStyle(color: colors.primary, borderRadius: borderRadius.md),
    sizes: FSizes.inherit(touch: touch),
    iconStyle: IconThemeData(color: colors.foreground, size: typography.lg.fontSize),
    tappableStyle: FTappableStyle(),
    extensions: [const Spacing(), const FPadding()],
  );
}

/// Provides convenient access to theme extensions on [FStyle].
///
/// ```dart
/// final spacing = context.theme.style.spacing; ✅
/// final padding = context.theme.style.padding; ✅
///
/// // Alternatively, you can create a getter to access extension fields directly.
/// final spacing = context.theme.style.spacing; ✅
///
/// final spacing = context.theme.style.extension<Spacing>(); ❌
/// ```
extension FStyleExtensions on FStyle {
  Spacing get spacing => extension<Spacing>();
  FPadding get padding => extension<FPadding>();
}
