import "package:flutter/cupertino.dart";
import "package:flutter/material.dart";
import "package:forui/forui.dart";
import "package:melodi/theme/styles/sidebar_item_style.dart";

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.touch.color,
///  style: FThemes.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.touch.color,
///    style: FThemes.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FSidebarGroupStyle sidebarGroupStyle({
  required FColors colors,
  required FTypography typography,
  required FIcons icons,
  required FStyle style,
  required bool touch,
}) => FSidebarGroupStyle(
  labelStyle: typography.xs.copyWith(
    color: colors.mutedForeground,
    overflow: .ellipsis,
    fontWeight: .w500,
  ),
  actionStyle: FVariants.from(
    IconThemeData(color: colors.mutedForeground, size: typography.md.fontSize),
    variants: {
      [.hovered, .pressed]: .delta(color: colors.foreground),
    },
  ),
  tappableStyle: style.tappableStyle,
  focusedOutlineStyle: style.focusedOutlineStyle,
  itemStyle: sidebarItemStyle(
    colors: colors,
    typography: typography,
    icons: icons,
    style: style,
    touch: touch,
  ),
  padding: const .symmetric(horizontal: 16),
  headerSpacing: 8,
  headerPadding: const .fromLTRB(8, 0, 8, 2),
  childrenSpacing: 4,
  childrenPadding: const .fromLTRB(0, 0, 0, 16),
);
