import "package:flutter/cupertino.dart";
import "package:flutter/material.dart";
import "package:forui/forui.dart";

// ignore_for_file: unnecessary_ignore
// ignore_for_file: avoid_redundant_argument_values

/// Generated by Forui CLI.
///
/// Modify the generated function bodies to create your own custom style.
/// Then, call the modified functions and pass the results to your FThemeData.
///
/// ### Example
/// Generated style:
/// ```dart
/// // Modify this function's body.
/// FDividerStyles dividerStyles({
///   required FColorScheme color,
///   required FStyle style,
/// }) => FDividerStyles(
///   horizontalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.horizontalStyle,
///     width: style.borderWidth,
///   ),
///   verticalStyle: FDividerStyle(
///     colors: colors.secondary,
///     padding: FDividerStyle.defaultPadding.verticalStyle,
///     width: style.borderWidth,
///   ),
/// );
/// ```
///
/// File that contains your `FThemeData`:
/// ```dart
/// import 'package:my_application/theme/divider_style.dart' // Your generated style file.
///
/// FThemeData(
///  color: FThemes.neutral.light.touch.color,
///  style: FThemes.neutral.light.touch.style,
///  dividerStyles: CustomFDividerStyles.dividerStyles( // The function in your generated style file.
///    color: FThemes.neutral.light.touch.color,
///    style: FThemes.neutral.light.touch.style,
///   ),
/// );
/// ```
///
/// A theme can be generated using the Forui CLI:
/// ```shell
/// dart forui theme create [theme name]
/// ```
///
/// See https://forui.dev/docs/guides/customizing-themes for more information.
FSidebarItemStyle sidebarItemStyle({
  required FColors colors,
  required FTypography typography,
  required FIcons icons,
  required FStyle style,
  required bool touch,
}) {
  EdgeInsetsGeometry padding;
  if (touch) {
    padding = const .symmetric(horizontal: 12, vertical: 14);
  } else {
    padding = const .all(8);
  }
  return FSidebarItemStyle(
    textStyle: .from(
      typography.sm.copyWith(color: colors.foreground, overflow: .ellipsis, height: 1),
      variants: {
        [.disabled]: .delta(color: colors.mutedForeground),
      },
    ),
    iconStyle: .from(
      IconThemeData(color: colors.foreground, size: 16),
      variants: {
        [.disabled]: .delta(color: colors.mutedForeground),
      },
    ),
    collapsibleIconStyle: .from(
      IconThemeData(color: colors.foreground, size: 16),
      variants: {
        [.disabled]: .delta(color: colors.mutedForeground),
      },
    ),
    collapsibleIcon: icons.chevronRight,
    backgroundColor: FVariants(
      colors.card,
      variants: {
        [.selected, .hovered, .pressed]: colors.muted,
        [.disabled]: colors.background,
      },
    ),
    padding: padding,
    borderRadius: style.borderRadius.md,
    tappableStyle: style.tappableStyle.copyWith(motion: FTappableMotion.none),
    focusedOutlineStyle: style.focusedOutlineStyle.copyWith(spacing: 0),
    iconSpacing: 8,
    collapsibleIconSpacing: 8,
    childrenSpacing: 4,
    childrenPadding: const .only(left: 26, top: 2),
    motion: const FSidebarItemMotion(),
  );
}
